class Commands:
    LEECH = "leech@SINNER_GT_bot"
    PURGE = "purge@SINNER_GT_bot"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "status@SINNER_GT_bot"
    SETTINGS = "settings"
    EXEC = "exec"
    UPLOAD = "upload@SINNER_GT_bot"
    YTDL = "ytdl@SINNER_GT_bot"
    PYTDL = "pytdl@SINNER_GT_bot"
    ABOUT = "about@SINNER_GT_bot"
    GETLOGS = "getlogs@SINNER_GT_bot"
    SERVER = "server@SINNER_GT_bot"
    USERSETTINGS = "usetting"
